// Code generated by pfw. DO NOT EDIT.
//go:build !pfw_inject

package main

import (
	fmt "fmt"
	httpserver "github.com/palma99/palma-framework/transport/httpserver"
)

func Initialize() (*Application, error) {
	value0 := NewStore()
	value1 := NewDocumentAuthorizer()
	value2 := NewDocumentService(value0, value1)
	value3 := NewDocumentController(value2)
	value4 := NewSessionCookieExtractor()
	value5 := NewSessionAuthenticator(value0)
	value6 := NewAppPrincipalResolver(value0)
	value7 := NewErrorMapper()
	value8, err := NewSecurityMiddleware(value4, value5, value6, value7)
	if err != nil {
		var zero *Application
		return zero, fmt.Errorf("pfw: github.com/palma99/palma-framework/examples/security.NewSecurityMiddleware: %w", err)
	}
	value9 := NewHTTPServer(value3, value8, value7)
	value10 := httpserver.New(value9)
	value11 := NewApplication(value10, value0, value2)
	return value11, nil
}
