// Code generated by pfw. DO NOT EDIT.
//go:build !pfw_inject

package main

import (
	errors "errors"
	fmt "fmt"
	sync "sync"
)

func Initialize() (*Service, func() error, error) {
	var close0 func() error
	var cleanupOnce sync.Once
	var cleanupErr error
	cleanup := func() error {
		cleanupOnce.Do(func() {
			if close0 != nil {
				if err := close0(); err != nil {
					cleanupErr = errors.Join(cleanupErr, fmt.Errorf("pfw: cleanup github.com/palma99/palma-framework/examples/cleanup.OpenDatabase: %w", err))
				}
				close0 = nil
			}
		})
		return cleanupErr
	}
	value0, close0, err := OpenDatabase()
	if err != nil {
		var zero *Service
		return zero, nil, errors.Join(fmt.Errorf("pfw: github.com/palma99/palma-framework/examples/cleanup.OpenDatabase: %w", err), cleanup())
	}
	value1 := NewService(value0)
	return value1, cleanup, nil
}
