// Code generated by pfw. DO NOT EDIT.
//go:build !pfw_inject

package bootstrap

import (
	fmt "fmt"
	config "github.com/palma99/palma-framework/examples/httpapi/internal/config"
	apihttp "github.com/palma99/palma-framework/examples/httpapi/internal/platform/http"
	userhttp "github.com/palma99/palma-framework/examples/httpapi/internal/user/adapter/http"
	memory "github.com/palma99/palma-framework/examples/httpapi/internal/user/adapter/memory"
	application "github.com/palma99/palma-framework/examples/httpapi/internal/user/application"
	http "net/http"
)

func Initialize(input0 config.Config) (*http.Server, error) {
	value0, err := memory.NewMemoryStore(input0)
	if err != nil {
		var zero *http.Server
		return zero, fmt.Errorf("pfw: github.com/palma99/palma-framework/examples/httpapi/internal/user/adapter/memory.NewMemoryStore: %w", err)
	}
	value1 := application.NewService(value0)
	value2 := userhttp.NewErrorMapper()
	value3 := userhttp.NewController(value1, value2)
	value4 := apihttp.Routes(value3)
	value5 := apihttp.Server(value4, input0)
	return value5, nil
}
