// Code generated by pfw. DO NOT EDIT.
//go:build !pfw_inject

package bootstrap

import (
	context "context"
	errors "errors"
	fmt "fmt"
	pfw "github.com/palma99/palma-framework"
	config "github.com/palma99/palma-framework/examples/httpapi/internal/config"
	apihttp "github.com/palma99/palma-framework/examples/httpapi/internal/platform/http"
	userhttp "github.com/palma99/palma-framework/examples/httpapi/internal/user/adapter/http"
	memory "github.com/palma99/palma-framework/examples/httpapi/internal/user/adapter/memory"
	application "github.com/palma99/palma-framework/examples/httpapi/internal/user/application"
	logging "github.com/palma99/palma-framework/logging"
	http "net/http"
)

func Initialize(input0 context.Context, input1 pfw.Environment, input2 config.Config) (*http.Server, func() error, error) {
	if input1 != "local" {
		var zero *http.Server
		return zero, nil, fmt.Errorf("pfw: environment %q does not match generated environment \"local\" for Initialize", input1)
	}
	cleanup := func() error { return nil }
	value0, err := memory.NewMemoryStore(input2)
	if err != nil {
		var zero *http.Server
		return zero, nil, errors.Join(fmt.Errorf("pfw: github.com/palma99/palma-framework/examples/httpapi/internal/user/adapter/memory.NewMemoryStore: %w", err), cleanup())
	}
	value1 := application.NewService(value0)
	value2 := userhttp.NewController(value1)
	value3 := userhttp.NewErrorMapper()
	value4 := logging.NewDefault()
	value5 := apihttp.Routes(value2, value3, value4)
	value6 := apihttp.Server(value5, input2)
	return value6, cleanup, nil
}
