package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strconv"
	"strings"
)

const generatedHeader = "// Code generated by pfw. DO NOT EDIT.\n"

type imports struct {
	local string
	names map[string]string
	used  map[string]bool
}

func (i *imports) qualify(pkg *types.Package) string {
	if pkg.Path() == i.local {
		return ""
	}
	return i.add(pkg.Path(), pkg.Name())
}

func (i *imports) add(path, preferred string) string {
	if name, ok := i.names[path]; ok {
		return name
	}
	name := i.fresh(preferred)
	i.names[path] = name
	return name
}

func (i *imports) fresh(base string) string {
	name := base
	for n := 1; i.used[name]; n++ {
		name = fmt.Sprintf("%s_%d", base, n)
	}
	i.used[name] = true
	return name
}

func emit(pkg *types.Package, initializers []initializer) ([]byte, error) {
	imp := imports{local: pkg.Path(), names: make(map[string]string), used: make(map[string]bool)}
	for _, name := range pkg.Scope().Names() {
		imp.used[name] = true
	}
	var body bytes.Buffer
	for _, init := range initializers {
		root := types.TypeString(init.root, imp.qualify)
		errName := imp.fresh("err")
		zeroName := imp.fresh("zero")
		values := make([]value, 0, len(init.graph.Inputs)+len(init.plan.Providers))
		fmt.Fprintf(&body, "func %s(", init.name)
		for n, input := range init.graph.Inputs {
			if n > 0 {
				body.WriteString(", ")
			}
			name := imp.fresh(input.Name)
			fmt.Fprintf(&body, "%s %s", name, types.TypeString(input.Type, imp.qualify))
			values = append(values, value{t: input.Type, name: name})
		}
		if init.withCleanup {
			fmt.Fprintf(&body, ") (%s, %s, error) {\n", root, types.TypeString(init.cleanupType, imp.qualify))
		} else {
			fmt.Fprintf(&body, ") (%s, error) {\n", root)
		}
		if init.environment != "" {
			envName := values[init.environmentIndex].name
			fmt.Fprintf(&body, "if %s != %q {\nvar %s %s\n", envName, init.environment, zeroName, root)
			failure := fmt.Sprintf("%s.Errorf(%q, %s)", imp.add("fmt", "fmt"), "pfw: environment %q does not match generated environment "+strconv.Quote(init.environment)+" for "+init.name, envName)
			if init.withCleanup {
				fmt.Fprintf(&body, "return %s, nil, %s\n}\n", zeroName, failure)
			} else {
				fmt.Fprintf(&body, "return %s, %s\n}\n", zeroName, failure)
			}
		}
		cleanupName := ""
		resourceCallbacks := make(map[string]string)
		if init.withCleanup {
			cleanupName = imp.fresh("cleanup")
			for n, p := range init.plan.Providers {
				if init.constructors[p.Name].cleanup {
					name := imp.fresh(fmt.Sprintf("close%d", n))
					resourceCallbacks[p.Name] = name
					fmt.Fprintf(&body, "var %s func() error\n", name)
				}
			}
			if len(resourceCallbacks) > 0 {
				onceName := imp.fresh("cleanupOnce")
				cleanupErr := imp.fresh("cleanupErr")
				fmt.Fprintf(&body, "var %s %s.Once\nvar %s error\n", onceName, imp.add("sync", "sync"), cleanupErr)
				fmt.Fprintf(&body, "%s := func() error {\n%s.Do(func() {\n", cleanupName, onceName)
				// Emit concrete calls in reverse order. Callbacks of providers not
				// reached during failed initialization remain nil.
				for n := len(init.plan.Providers) - 1; n >= 0; n-- {
					p := init.plan.Providers[n]
					if name, ok := resourceCallbacks[p.Name]; ok {
						fmt.Fprintf(&body, "if %s != nil {\nif %s := %s(); %s != nil {\n", name, errName, name, errName)
						fmt.Fprintf(&body, "%s = %s.Join(%s, %s.Errorf(%s, %s))\n}\n%s = nil\n}\n", cleanupErr, imp.add("errors", "errors"), cleanupErr, imp.add("fmt", "fmt"), strconv.Quote("pfw: cleanup "+p.Name+": %w"), errName, name)
					}
				}
				fmt.Fprintf(&body, "})\nreturn %s\n}\n", cleanupErr)
			} else {
				fmt.Fprintf(&body, "%s := func() error { return nil }\n", cleanupName)
			}
		}
		for n, provider := range init.plan.Providers {
			ctor := init.constructors[provider.Name]
			callee := ctor.fn.Name()
			if qualifier := imp.qualify(ctor.fn.Pkg()); qualifier != "" {
				callee = qualifier + "." + callee
			}
			if len(ctor.typeArgs) > 0 {
				var arguments []string
				for _, argument := range ctor.typeArgs {
					arguments = append(arguments, types.TypeString(argument, imp.qualify))
				}
				callee += "[" + strings.Join(arguments, ", ") + "]"
			}
			var args []string
			for _, input := range provider.Inputs {
				name, err := lookup(init, values, input, provider.Name)
				if err != nil {
					return nil, err
				}
				args = append(args, name)
			}
			name := imp.fresh(fmt.Sprintf("value%d", n))
			if ctor.fallible {
				if ctor.cleanup {
					// Assignment transfers callback ownership even when err is non-nil.
					fmt.Fprintf(&body, "%s, %s, %s := %s(%s)\n", name, resourceCallbacks[provider.Name], errName, callee, strings.Join(args, ", "))
				} else {
					fmt.Fprintf(&body, "%s, %s := %s(%s)\n", name, errName, callee, strings.Join(args, ", "))
				}
				wrapped := fmt.Sprintf("%s.Errorf(%s, %s)", imp.add("fmt", "fmt"), strconv.Quote("pfw: "+provider.Name+": %w"), errName)
				fmt.Fprintf(&body, "if %s != nil {\nvar %s %s\n", errName, zeroName, root)
				if init.withCleanup {
					fmt.Fprintf(&body, "return %s, nil, %s.Join(%s, %s())\n}\n", zeroName, imp.add("errors", "errors"), wrapped, cleanupName)
				} else {
					fmt.Fprintf(&body, "return %s, %s\n}\n", zeroName, wrapped)
				}
			} else {
				fmt.Fprintf(&body, "%s := %s(%s)\n", name, callee, strings.Join(args, ", "))
			}
			values = append(values, value{t: provider.Output, name: name})
		}
		rootName, err := lookup(init, values, init.root, "")
		if err != nil {
			return nil, err
		}
		if init.withCleanup {
			fmt.Fprintf(&body, "return %s, %s, nil\n}\n\n", rootName, cleanupName)
		} else {
			fmt.Fprintf(&body, "return %s, nil\n}\n\n", rootName)
		}
	}
	var source bytes.Buffer
	fmt.Fprintf(&source, "%s//go:build !pfw_inject\n\npackage %s\n\n", generatedHeader, pkg.Name())
	if len(imp.names) > 0 {
		paths := make([]string, 0, len(imp.names))
		for path := range imp.names {
			paths = append(paths, path)
		}
		sort.Strings(paths)
		source.WriteString("import (\n")
		for _, path := range paths {
			fmt.Fprintf(&source, "%s %q\n", imp.names[path], path)
		}
		source.WriteString(")\n\n")
	}
	source.Write(body.Bytes())
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

type value struct {
	t    types.Type
	name string
}

func lookup(init initializer, values []value, t types.Type, consumer string) (string, error) {
	for _, binding := range init.plan.Selections {
		if binding.Consumer == consumer && types.Identical(t, binding.Interface) {
			t = binding.Concrete
			break
		}
	}
	for _, v := range values {
		if types.Identical(t, v.t) {
			return v.name, nil
		}
	}
	return "", fmt.Errorf("internal error: unresolved value %s in %s", t, init.name)
}
